#!/usr/bin/env bash
# localhost resolves and facebook.com resolves 

sed -i '/localhost/d' /etc/hosts
sed -i '/facebook.com/d' /etc/hosts
echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
cat /etc/hosts